# Generated by Django 4.1.3 on 2022-11-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelTable(
            name='todomodel',
            table='Myname',
        ),
    ]
