# Generated by Django 4.1.3 on 2022-11-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_todomodel_options_alter_todomodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todomodel',
            table=None,
        ),
    ]
